name: Build iOS Tweak with Theos
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Theos Environment
        run: |
          export THEOS=~/theos
          bash -c "$(curl -fsSL https://githubusercontent.com)"
          curl -LO https://github.com
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $THEOS/sdks/
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Tweak using Makefile
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1

      - name: Upload Finished Dylib
        uses: actions/upload-artifact@v4
        with:
          name: KeySystem-Dylib
          path: .theos/obj/debug/SecurityKey.dylib
